-- meta.metric -- the metric-catalog registry table (ADR-291,
-- openspec/changes/metric-catalog/). One row per
-- mlb_baseball/metrics/<name>.yaml entry, generated (never hand-edited) by
-- `mlb catalog build` (mlb_baseball/catalog.py::load()) -- same idempotent
-- full-rebuild pattern as every other gold/meta loader in this project
-- (TRUNCATE + insert every validated entry in one transaction, see
-- conform._build_team_aliases).
--
-- This is documentation-only tooling: it records which statistic exists,
-- where its formula lives, whose idea it is (citation) vs. which tables its
-- numbers come from (data_source), how it's implemented, its validation
-- status, and its public/internal visibility. It does not compute, store, or
-- change any metric's actual value.
--
-- source_permalink is generated by the loader from `formula` + the git
-- commit the catalog build ran against -- never hand-written in the YAML,
-- never pointing at a moving branch (design.md Decision 7).
--
-- Additive and reversible: rollback is `DROP TABLE meta.metric;`. No other
-- system depends on it yet.

CREATE TABLE IF NOT EXISTS meta.metric (
    name             text PRIMARY KEY,
    definition       text NOT NULL,
    formula          text NOT NULL,
    citation         text NOT NULL,
    data_source      text NOT NULL,
    grain            text NOT NULL,
    layer            text NOT NULL
        CHECK (layer IN ('gold', 'feat', 'model')),
    complexity       text NOT NULL
        CHECK (complexity IN ('arithmetic', 'complex')),
    implementation   text NOT NULL
        CHECK (implementation IN ('sql', 'sqlmesh', 'python')),
    status           text NOT NULL
        CHECK (status IN (
            'published', 'validated', 'implemented-untested',
            'negative-result', 'archived'
        )),
    visibility       text NOT NULL
        CHECK (visibility IN ('public', 'internal')),
    test_ref         text,
    notes            text,
    source_permalink text NOT NULL,
    loaded_at        timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE meta.metric IS
    'Generated metric catalog registry (ADR-291) -- rebuilt in full by '
    '`mlb catalog build` from mlb_baseball/metrics/*.yaml. Never hand-edited; '
    'never a metric-computation input.';
