"""Generated index of the `mlb` upkeep commands (docs/COMMANDS.md).

Built from the argparse tree so the docs cannot drift from the code: a test regenerates the
index and fails when `docs/COMMANDS.md` is stale. Regenerate with
`python -m mlb_baseball.command_index > docs/COMMANDS.md`. The effect column is the one fact
argparse cannot tell, so it is declared here for the upkeep commands only.
"""

import argparse

# command -> what it changes. Commands not listed are research or reporting tools, not upkeep.
EFFECTS: dict[str, str] = {
    "migrate": "writes: database schema",
    "ingest": "writes: raw tables (use --dry-run to preview)",
    "bootstrap": "writes: raw tables for every source",
    "update": "writes: raw tables for every source",
    "conform": "writes: core tables",
    "report": "writes: gold tables",
    "odds-capture": "writes: raw price snapshots",
    "nightly": "writes: the whole daily pipeline",
    "repair": "dry run by default; --apply writes (safe-listed ingests only)",
    "repair-runs": "writes: closes stale run records",
    "backfill-game-identities": "writes: core game identities",
    "schema-watch": "writes: snapshot files and meta.schema_finding, never raw",
    "coverage": "read-only",
    "source-check": "read-only (HEAD requests; --hash downloads to a temp file)",
    "field-census": "read-only",
    "inventory": "read-only (--save-profile writes meta.raw_profile)",
    "schema": "read-only",
    "status": "read-only",
    "doctor": "read-only",
    "audit": "read-only",
    "preflight": "read-only",
    "runs": "read-only",
    "metrics": "read-only",
    "backup": "reads the database, writes a dump file",
    "restore": "DESTRUCTIVE: overwrites the database",
}


def _parser() -> argparse.ArgumentParser:
    """The real parser, captured without running a command."""
    from mlb_baseball import cli

    class _Captured(Exception):
        pass

    original = argparse.ArgumentParser.parse_args

    def capture(self, *args, **kwargs):
        raise _Captured(self)

    argparse.ArgumentParser.parse_args = capture  # type: ignore[method-assign]
    try:
        cli.main(["status"])
    except _Captured as found:
        return found.args[0]
    finally:
        argparse.ArgumentParser.parse_args = original  # type: ignore[method-assign]
    raise RuntimeError("cli.main did not reach parse_args")


def build() -> str:
    parser = _parser()
    subparsers = next(a for a in parser._actions if isinstance(a, argparse._SubParsersAction))
    helps = {a.dest: (a.help or "") for a in subparsers._choices_actions}
    lines = [
        "# `mlb` upkeep commands",
        "",
        "Generated by `python -m mlb_baseball.command_index`; a test fails when it is stale.",
        "Only upkeep commands are listed (data loading, checking, repair); research and chart",
        "commands are in `mlb --help`.",
        "",
        "| Command | Effect | Flags | JSON | Dry run |",
        "|---|---|---|---|---|",
    ]
    for name, effect in EFFECTS.items():
        sub = subparsers.choices[name]
        flags = sorted({o for a in sub._actions for o in a.option_strings} - {"-h", "--help"})
        json_out = "yes" if "--json" in flags else "no"
        dry = "yes" if "--dry-run" in flags or name in ("preflight",) else "no"
        shown = " ".join(f"`{f}`" for f in flags) or "none"
        lines.append(f"| `mlb {name}` | {effect} | {shown} | {json_out} | {dry} |")
    lines += [
        "",
        f"Help text for each command: `mlb <command> --help` ({len(helps)} commands in all).",
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    print(build(), end="")
