"""Pinned Retrosheet raw-table column contract (task 2.6, design D6).

Every ``raw.retrosheet_*`` table this repository's tie-out gate compares (see
``tieout_run.SOURCES``) must expose exactly these columns. This is a pin, not
a guess: it was captured by reading ``information_schema.columns`` against the
real production ``mlb`` database (read-only) on 2026-09-27, the same evidence
standard used throughout this change (see ``passmarks.md``).

The gate's schema check (``tieout_run.run_schema_check``) reads production's
``information_schema`` again on every run and fails on any column this
contract expects but the table no longer has, or any column the table now has
that this contract does not expect -- so a silent source-header change (a
Retrosheet field added or renamed, a connector regenerating a table with a
different Chadwick field spec) is caught instead of quietly changing what the
rest of the gate certifies.

Re-pin (regenerate this file) deliberately, after confirming the new columns
are intended, not to make a failing run pass.
"""

# ruff: noqa: E501

from __future__ import annotations

# fmt: off
RAW_SCHEMA_CONTRACT: dict[str, frozenset[str]] = {
    "raw.retrosheet_allplayers": frozenset({
        'id', 'last', 'first', 'bat',
        'throw', 'team', 'g', 'g_p',
        'g_sp', 'g_rp', 'g_c', 'g_1b',
        'g_2b', 'g_3b', 'g_ss', 'g_lf',
        'g_cf', 'g_rf', 'g_of', 'g_dh',
        'g_ph', 'g_pr', 'first_g', 'last_g',
        '_season', '_loaded_at',
    }),
    "raw.retrosheet_batting": frozenset({
        'gid', 'id', 'team', 'b_lp',
        'b_seq', 'stattype', 'b_pa', 'b_ab',
        'b_r', 'b_h', 'b_d', 'b_t',
        'b_hr', 'b_rbi', 'b_sh', 'b_sf',
        'b_hbp', 'b_w', 'b_iw', 'b_k',
        'b_sb', 'b_cs', 'b_gdp', 'b_xi',
        'b_roe', 'dh', 'ph', 'pr',
        'date', 'number', 'site', 'vishome',
        'opp', 'win', 'loss', 'tie',
        'gametype', 'box', 'pbp', '_season',
        '_loaded_at',
    }),
    "raw.retrosheet_box_batting": frozenset({
        'game_id', 'team', 'id', 'lname',
        'fname', 'slot', 'seq', 'start_pos',
        'ab', 'r', 'h', 'd',
        't', 'hr', 'bi', 'bi2out',
        'bb', 'ibb', 'so', 'gdp',
        'hp', 'sh', 'sf', 'sb',
        'cs', '_season', '_group', '_scope',
        '_loaded_at',
    }),
    "raw.retrosheet_box_game": frozenset({
        'game_id', 'date', 'site', 'visitor',
        'visitor_city', 'visitor_name', 'home', 'home_city',
        'home_name', 'start_time', 'day_night', 'temperature',
        'wind_direction', 'wind_speed', 'field_condition', 'precip',
        'sky', 'time_of_game', 'attendance', 'umpire_hp',
        'umpire_1b', 'umpire_2b', 'umpire_3b', 'htbf',
        'linescore_away_runs', 'linescore_away_hits', 'linescore_away_errors', 'linescore_home_runs',
        'linescore_home_hits', 'linescore_home_errors', '_season', '_group',
        '_scope', '_loaded_at', 'umpire_lf', 'umpire_rf',
    }),
    "raw.retrosheet_event": frozenset({
        'game_id', 'away_team_id', 'inn_ct', 'bat_home_id',
        'outs_ct', 'balls_ct', 'strikes_ct', 'pitch_seq_tx',
        'away_score_ct', 'home_score_ct', 'bat_id', 'bat_hand_cd',
        'resp_bat_id', 'resp_bat_hand_cd', 'pit_id', 'pit_hand_cd',
        'resp_pit_id', 'resp_pit_hand_cd', 'pos2_fld_id', 'pos3_fld_id',
        'pos4_fld_id', 'pos5_fld_id', 'pos6_fld_id', 'pos7_fld_id',
        'pos8_fld_id', 'pos9_fld_id', 'base1_run_id', 'base2_run_id',
        'base3_run_id', 'event_tx', 'leadoff_fl', 'ph_fl',
        'bat_fld_cd', 'bat_lineup_id', 'event_cd', 'bat_event_fl',
        'ab_fl', 'h_cd', 'sh_fl', 'sf_fl',
        'event_outs_ct', 'dp_fl', 'tp_fl', 'rbi_ct',
        'wp_fl', 'pb_fl', 'fld_cd', 'battedball_cd',
        'bunt_fl', 'foul_fl', 'battedball_loc_tx', 'err_ct',
        'err1_fld_cd', 'err1_cd', 'err2_fld_cd', 'err2_cd',
        'err3_fld_cd', 'err3_cd', 'bat_dest_id', 'run1_dest_id',
        'run2_dest_id', 'run3_dest_id', 'bat_play_tx', 'run1_play_tx',
        'run2_play_tx', 'run3_play_tx', 'run1_sb_fl', 'run2_sb_fl',
        'run3_sb_fl', 'run1_cs_fl', 'run2_cs_fl', 'run3_cs_fl',
        'run1_pk_fl', 'run2_pk_fl', 'run3_pk_fl', 'run1_resp_pit_id',
        'run2_resp_pit_id', 'run3_resp_pit_id', 'game_new_fl', 'game_end_fl',
        'pr_run1_fl', 'pr_run2_fl', 'pr_run3_fl', 'removed_for_pr_run1_id',
        'removed_for_pr_run2_id', 'removed_for_pr_run3_id', 'removed_for_ph_bat_id', 'removed_for_ph_bat_fld_cd',
        'po1_fld_cd', 'po2_fld_cd', 'po3_fld_cd', 'ass1_fld_cd',
        'ass2_fld_cd', 'ass3_fld_cd', 'ass4_fld_cd', 'ass5_fld_cd',
        'event_id', 'home_team_id', 'bat_team_id', 'fld_team_id',
        'bat_last_id', 'inn_new_fl', 'inn_end_fl', 'start_bat_score_ct',
        'start_fld_score_ct', 'inn_runs_ct', 'game_pa_ct', 'inn_pa_ct',
        'pa_new_fl', 'pa_trunc_fl', 'start_bases_cd', 'end_bases_cd',
        'bat_start_fl', 'resp_bat_start_fl', 'bat_on_deck_id', 'bat_in_hold_id',
        'pit_start_fl', 'resp_pit_start_fl', 'run1_fld_cd', 'run1_lineup_cd',
        'run1_origin_event_id', 'run2_fld_cd', 'run2_lineup_cd', 'run2_origin_event_id',
        'run3_fld_cd', 'run3_lineup_cd', 'run3_origin_event_id', 'run1_resp_cat_id',
        'run2_resp_cat_id', 'run3_resp_cat_id', 'pa_ball_ct', 'pa_called_ball_ct',
        'pa_intent_ball_ct', 'pa_pitchout_ball_ct', 'pa_hitbatter_ball_ct', 'pa_other_ball_ct',
        'pa_strike_ct', 'pa_called_strike_ct', 'pa_swingmiss_strike_ct', 'pa_foul_strike_ct',
        'pa_inplay_strike_ct', 'pa_other_strike_ct', 'event_runs_ct', 'fld_id',
        'base2_force_fl', 'base3_force_fl', 'base4_force_fl', 'bat_safe_err_fl',
        'bat_fate_id', 'run1_fate_id', 'run2_fate_id', 'run3_fate_id',
        'fate_runs_ct', 'ass6_fld_cd', 'ass7_fld_cd', 'ass8_fld_cd',
        'ass9_fld_cd', 'ass10_fld_cd', 'unknown_out_exc_fl', 'uncertain_play_exc_fl',
        'count_tx', 'run1_auto_fl', 'run2_auto_fl', 'run3_auto_fl',
        '_season', '_group', '_scope', '_loaded_at',
    }),
    "raw.retrosheet_gameinfo": frozenset({
        'gid', 'visteam', 'hometeam', 'site',
        'date', 'number', 'starttime', 'daynight',
        'innings', 'tiebreaker', 'usedh', 'htbf',
        'timeofgame', 'attendance', 'fieldcond', 'precip',
        'sky', 'temp', 'winddir', 'windspeed',
        'oscorer', 'forfeit', 'suspend', 'umphome',
        'ump1b', 'ump2b', 'ump3b', 'umplf',
        'umprf', 'wp', 'lp', 'save',
        'gametype', 'vruns', 'hruns', 'wteam',
        'lteam', 'line', 'batteries', 'lineups',
        'box', 'pbp', 'season', '_season',
        '_loaded_at',
    }),
    "raw.retrosheet_gamelog": frozenset({
        'date', 'game_number', 'day_of_week', 'v_team',
        'v_league', 'v_game_number', 'h_team', 'h_league',
        'h_game_number', 'v_score', 'h_score', 'length_outs',
        'day_night', 'completion', 'forfeit', 'protest',
        'park_id', 'attendance', 'time_of_game_minutes', 'v_line_score',
        'h_line_score', 'v_at_bats', 'v_hits', 'v_doubles',
        'v_triples', 'v_homeruns', 'v_rbi', 'v_sac_hits',
        'v_sac_flies', 'v_hbp', 'v_walks', 'v_intentional_walks',
        'v_strikeouts', 'v_stolen_bases', 'v_caught_stealing', 'v_grounded_into_dp',
        'v_first_on_catcher_interference', 'v_left_on_base', 'v_pitchers_used', 'v_individual_earned_runs',
        'v_team_earned_runs', 'v_wild_pitches', 'v_balks', 'v_putouts',
        'v_assists', 'v_errors', 'v_passed_balls', 'v_double_plays',
        'v_triple_plays', 'h_at_bats', 'h_hits', 'h_doubles',
        'h_triples', 'h_homeruns', 'h_rbi', 'h_sac_hits',
        'h_sac_flies', 'h_hbp', 'h_walks', 'h_intentional_walks',
        'h_strikeouts', 'h_stolen_bases', 'h_caught_stealing', 'h_grounded_into_dp',
        'h_first_on_catcher_interference', 'h_left_on_base', 'h_pitchers_used', 'h_individual_earned_runs',
        'h_team_earned_runs', 'h_wild_pitches', 'h_balks', 'h_putouts',
        'h_assists', 'h_errors', 'h_passed_balls', 'h_double_plays',
        'h_triple_plays', 'ump_home_id', 'ump_home_name', 'ump_1b_id',
        'ump_1b_name', 'ump_2b_id', 'ump_2b_name', 'ump_3b_id',
        'ump_3b_name', 'ump_lf_id', 'ump_lf_name', 'ump_rf_id',
        'ump_rf_name', 'v_manager_id', 'v_manager_name', 'h_manager_id',
        'h_manager_name', 'winning_pitcher_id', 'winning_pitcher_name', 'losing_pitcher_id',
        'losing_pitcher_name', 'saving_pitcher_id', 'saving_pitcher_name', 'gwrbi_batter_id',
        'gwrbi_batter_name', 'v_starting_pitcher_id', 'v_starting_pitcher_name', 'h_starting_pitcher_id',
        'h_starting_pitcher_name', 'v_player1_id', 'v_player1_name', 'v_player1_pos',
        'v_player2_id', 'v_player2_name', 'v_player2_pos', 'v_player3_id',
        'v_player3_name', 'v_player3_pos', 'v_player4_id', 'v_player4_name',
        'v_player4_pos', 'v_player5_id', 'v_player5_name', 'v_player5_pos',
        'v_player6_id', 'v_player6_name', 'v_player6_pos', 'v_player7_id',
        'v_player7_name', 'v_player7_pos', 'v_player8_id', 'v_player8_name',
        'v_player8_pos', 'v_player9_id', 'v_player9_name', 'v_player9_pos',
        'h_player1_id', 'h_player1_name', 'h_player1_pos', 'h_player2_id',
        'h_player2_name', 'h_player2_pos', 'h_player3_id', 'h_player3_name',
        'h_player3_pos', 'h_player4_id', 'h_player4_name', 'h_player4_pos',
        'h_player5_id', 'h_player5_name', 'h_player5_pos', 'h_player6_id',
        'h_player6_name', 'h_player6_pos', 'h_player7_id', 'h_player7_name',
        'h_player7_pos', 'h_player8_id', 'h_player8_name', 'h_player8_pos',
        'h_player9_id', 'h_player9_name', 'h_player9_pos', 'additional_info',
        'acquisition_info', '_season', '_loaded_at',
    }),
    "raw.retrosheet_gamelog_post": frozenset({
        'date', 'game_number', 'day_of_week', 'v_team',
        'v_league', 'v_game_number', 'h_team', 'h_league',
        'h_game_number', 'v_score', 'h_score', 'length_outs',
        'day_night', 'completion', 'forfeit', 'protest',
        'park_id', 'attendance', 'time_of_game_minutes', 'v_line_score',
        'h_line_score', 'v_at_bats', 'v_hits', 'v_doubles',
        'v_triples', 'v_homeruns', 'v_rbi', 'v_sac_hits',
        'v_sac_flies', 'v_hbp', 'v_walks', 'v_intentional_walks',
        'v_strikeouts', 'v_stolen_bases', 'v_caught_stealing', 'v_grounded_into_dp',
        'v_first_on_catcher_interference', 'v_left_on_base', 'v_pitchers_used', 'v_individual_earned_runs',
        'v_team_earned_runs', 'v_wild_pitches', 'v_balks', 'v_putouts',
        'v_assists', 'v_errors', 'v_passed_balls', 'v_double_plays',
        'v_triple_plays', 'h_at_bats', 'h_hits', 'h_doubles',
        'h_triples', 'h_homeruns', 'h_rbi', 'h_sac_hits',
        'h_sac_flies', 'h_hbp', 'h_walks', 'h_intentional_walks',
        'h_strikeouts', 'h_stolen_bases', 'h_caught_stealing', 'h_grounded_into_dp',
        'h_first_on_catcher_interference', 'h_left_on_base', 'h_pitchers_used', 'h_individual_earned_runs',
        'h_team_earned_runs', 'h_wild_pitches', 'h_balks', 'h_putouts',
        'h_assists', 'h_errors', 'h_passed_balls', 'h_double_plays',
        'h_triple_plays', 'ump_home_id', 'ump_home_name', 'ump_1b_id',
        'ump_1b_name', 'ump_2b_id', 'ump_2b_name', 'ump_3b_id',
        'ump_3b_name', 'ump_lf_id', 'ump_lf_name', 'ump_rf_id',
        'ump_rf_name', 'v_manager_id', 'v_manager_name', 'h_manager_id',
        'h_manager_name', 'winning_pitcher_id', 'winning_pitcher_name', 'losing_pitcher_id',
        'losing_pitcher_name', 'saving_pitcher_id', 'saving_pitcher_name', 'gwrbi_batter_id',
        'gwrbi_batter_name', 'v_starting_pitcher_id', 'v_starting_pitcher_name', 'h_starting_pitcher_id',
        'h_starting_pitcher_name', 'v_player1_id', 'v_player1_name', 'v_player1_pos',
        'v_player2_id', 'v_player2_name', 'v_player2_pos', 'v_player3_id',
        'v_player3_name', 'v_player3_pos', 'v_player4_id', 'v_player4_name',
        'v_player4_pos', 'v_player5_id', 'v_player5_name', 'v_player5_pos',
        'v_player6_id', 'v_player6_name', 'v_player6_pos', 'v_player7_id',
        'v_player7_name', 'v_player7_pos', 'v_player8_id', 'v_player8_name',
        'v_player8_pos', 'v_player9_id', 'v_player9_name', 'v_player9_pos',
        'h_player1_id', 'h_player1_name', 'h_player1_pos', 'h_player2_id',
        'h_player2_name', 'h_player2_pos', 'h_player3_id', 'h_player3_name',
        'h_player3_pos', 'h_player4_id', 'h_player4_name', 'h_player4_pos',
        'h_player5_id', 'h_player5_name', 'h_player5_pos', 'h_player6_id',
        'h_player6_name', 'h_player6_pos', 'h_player7_id', 'h_player7_name',
        'h_player7_pos', 'h_player8_id', 'h_player8_name', 'h_player8_pos',
        'h_player9_id', 'h_player9_name', 'h_player9_pos', 'additional_info',
        'acquisition_info', '_type', '_loaded_at',
    }),
    "raw.retrosheet_plays": frozenset({
        'gid', 'event', 'inning', 'top_bot',
        'vis_home', 'site', 'batteam', 'pitteam',
        'score_v', 'score_h', 'batter', 'pitcher',
        'lp', 'bat_f', 'bathand', 'pithand',
        'balls', 'strikes', 'count', 'pitches',
        'nump', 'pa', 'ab', 'single',
        'double', 'triple', 'hr', 'sh',
        'sf', 'hbp', 'walk', 'k',
        'xi', 'roe', 'fc', 'othout',
        'noout', 'oth', 'bip', 'bunt',
        'ground', 'fly', 'line', 'iw',
        'gdp', 'othdp', 'tp', 'fle',
        'wp', 'pb', 'bk', 'oa',
        'di', 'sb2', 'sb3', 'sbh',
        'cs2', 'cs3', 'csh', 'pko1',
        'pko2', 'pko3', 'k_safe', 'e1',
        'e2', 'e3', 'e4', 'e5',
        'e6', 'e7', 'e8', 'e9',
        'outs_pre', 'outs_post', 'br1_pre', 'br2_pre',
        'br3_pre', 'br1_post', 'br2_post', 'br3_post',
        'lob_id1', 'lob_id2', 'lob_id3', 'pr1_pre',
        'pr2_pre', 'pr3_pre', 'pr1_post', 'pr2_post',
        'pr3_post', 'run_b', 'run1', 'run2',
        'run3', 'prun_b', 'prun1', 'prun2',
        'prun3', 'ur_b', 'ur1', 'ur2',
        'ur3', 'rbi_b', 'rbi1', 'rbi2',
        'rbi3', 'runs', 'rbi', 'er',
        'tur', 'l1', 'l2', 'l3',
        'l4', 'l5', 'l6', 'l7',
        'l8', 'l9', 'lf1', 'lf2',
        'lf3', 'lf4', 'lf5', 'lf6',
        'lf7', 'lf8', 'lf9', 'f2',
        'f3', 'f4', 'f5', 'f6',
        'f7', 'f8', 'f9', 'po0',
        'po1', 'po2', 'po3', 'po4',
        'po5', 'po6', 'po7', 'po8',
        'po9', 'a1', 'a2', 'a3',
        'a4', 'a5', 'a6', 'a7',
        'a8', 'a9', 'fseq', 'batout1',
        'batout2', 'batout3', 'brout_b', 'brout1',
        'brout2', 'brout3', 'firstf', 'loc',
        'hittype', 'dpopp', 'pivot', 'pn',
        'umphome', 'ump1b', 'ump2b', 'ump3b',
        'umplf', 'umprf', 'date', 'gametype',
        'pbp', '_season', '_loaded_at',
    }),
    "raw.retrosheet_roster": frozenset({
        'player_id', 'last_name', 'first_name', 'bats',
        'throws', 'team_id', 'position', '_season',
        '_loaded_at',
    }),
}
# fmt: on
