"""Batter Two-Strike Expansion Resistance & Out-of-Zone Foul Engine (EXP-RESIST-01, ADR-208).

Provides two-strike chase suppression, out-of-zone contact, and foul survival modeling:
1. Two-Strike Expansion Resistance Index (TERI score measuring discipline and contact).
2. Out-of-Zone Contact & Foul Spoil Surplus (runs generated by prolonging two-strike counts).
3. Resistance Archetypes (Elite Expansion Resistor, Foul Ball Spoiler, Chase Victim).

Adheres strictly to object-oriented encapsulation, polymorphic protocols, and
point-in-time correctness with zero lookahead leakage.
"""

from __future__ import annotations

import dataclasses
from typing import Protocol

from mlb_baseball.health import Check


@dataclasses.dataclass(frozen=True)
class BatterExpansionResistanceMetrics:
    """Observed batter two-strike chase rate, out-of-zone contact, and foul rate."""

    batter_id: str
    batter_name: str
    two_strike_chase_pct: float = 34.0  # League average ~36.0%
    two_strike_o_contact_pct: float = 56.0  # League average ~54.0%
    two_strike_foul_pct: float = 42.0  # League average ~40.0%
    two_strike_pa_count: int = 250


@dataclasses.dataclass(frozen=True)
class ExpansionResistanceEvaluationResult:
    """Evaluated two-strike expansion resistance, TERI score, and run value."""

    batter_name: str
    teri_score: float  # Two-Strike Expansion Resistance Index (0 to 160)
    runs_value: float  # Surplus runs generated from prolonged two-strike battles
    resistance_tier: str  # e.g. "ELITE_ZONE_EXPANSION_RESISTOR", "CHASE_PRONE_VICTIM"
    is_elite_resistor: bool


class BaseExpansionResistanceEngine(Protocol):
    """Polymorphic protocol for two-strike expansion resistance engines."""

    def evaluate_resistance(
        self,
        metrics: BatterExpansionResistanceMetrics,
    ) -> ExpansionResistanceEvaluationResult:
        """Calculate TERI score and two-strike battle run value."""
        ...


class BatterExpansionResistanceEngine:
    """Calculates two-strike chase suppression, foul survival, and run value (EXP-RESIST-01)."""

    def evaluate_resistance(
        self,
        metrics: BatterExpansionResistanceMetrics,
    ) -> ExpansionResistanceEvaluationResult:
        """Compute TERI score and two-strike surplus run generation."""
        # TERI Score: benchmark 36.0% chase, 54.0% O-Contact, 40.0% foul
        chase_bonus = (36.0 - metrics.two_strike_chase_pct) * 2.5
        ocontact_bonus = (metrics.two_strike_o_contact_pct - 54.0) * 1.8
        foul_bonus = (metrics.two_strike_foul_pct - 40.0) * 1.2
        teri = round(max(0.0, 100.0 + chase_bonus + ocontact_bonus + foul_bonus), 1)

        # Runs generated: prolonged at-bats extract run value (~0.0035 per point over 100 per PA)
        pas = max(1, metrics.two_strike_pa_count)
        runs = round((teri - 100.0) * (pas * 0.0035), 2)

        is_elite = (
            teri >= 118.0
            and metrics.two_strike_chase_pct <= 28.0
            and metrics.two_strike_o_contact_pct >= 60.0
        )

        # Tiers
        if is_elite:
            tier = "ELITE_ZONE_EXPANSION_RESISTOR"
        elif metrics.two_strike_chase_pct >= 42.0:
            tier = "CHASE_PRONE_TWO_STRIKE_VICTIM"
        elif metrics.two_strike_foul_pct >= 46.0:
            tier = "TWO_STRIKE_FOUL_BALL_SPOILER"
        else:
            tier = "AVERAGE_TWO_STRIKE_RESISTANCE"

        return ExpansionResistanceEvaluationResult(
            batter_name=metrics.batter_name,
            teri_score=teri,
            runs_value=runs,
            resistance_tier=tier,
            is_elite_resistor=is_elite,
        )


def health_check() -> list[Check]:
    """Operational health check for Batter Expansion Resistance Engine (EXP-RESIST-01)."""
    checks: list[Check] = []
    try:
        engine = BatterExpansionResistanceEngine()
        battler = BatterExpansionResistanceMetrics("b1", "Steven Kwan", 22.0, 72.0, 50.0, 300)
        chaser = BatterExpansionResistanceMetrics("b2", "Free Swinger", 45.0, 42.0, 32.0, 220)

        r_bat = engine.evaluate_resistance(battler)
        r_cha = engine.evaluate_resistance(chaser)

        if (
            r_bat.resistance_tier == "ELITE_ZONE_EXPANSION_RESISTOR"
            and r_cha.resistance_tier == "CHASE_PRONE_TWO_STRIKE_VICTIM"
        ):
            checks.append(
                Check(
                    "exp resist engine",
                    True,
                    f"Exp Resist verified (Kwan TERI: {r_bat.teri_score:.1f})",
                )
            )
        else:
            checks.append(
                Check("exp resist engine", False, f"Unexpected exp resist output: {r_bat}, {r_cha}")
            )
    except Exception as exc:
        checks.append(Check("exp resist engine", False, str(exc)))
    return checks
