"""Batter Two-Strike Foul Attrition & Pitcher Exhaustion Engine (FOUL-ATTRITION-01, ADR-216).

Provides multi-foul plate appearance endurance and starter attrition modeling:
1. Batter Foul Attrition Index (BFAI score measuring pitch extraction efficiency).
2. Starter Removal Acceleration Runs (SRAR net runs generated by chasing starting pitchers early).
3. Attrition Archetypes (Exhausting Foul Ball Grinder, Rapid Dismissal Free Swinger).

Adheres strictly to object-oriented encapsulation, polymorphic protocols, and
point-in-time correctness with zero lookahead leakage.
"""

from __future__ import annotations

import dataclasses
from typing import Protocol

from mlb_baseball.health import Check


@dataclasses.dataclass(frozen=True)
class BatterFoulAttritionMetrics:
    """Observed batter multi-foul frequency, pitches seen per PA, and 2-strike foul rate."""

    batter_id: str
    batter_name: str
    multi_foul_pa_rate_pct: float = (
        11.0  # Fraction of 2-strike PAs with >= 3 fouls (benchmark ~11.0%)
    )
    pitches_per_pa: float = 3.95  # Average pitches per PA (benchmark ~3.95)
    two_strike_foul_rate_pct: float = 42.0  # Foul % on 2-strike swings (benchmark ~42.0%)
    total_pa_count: int = 500


@dataclasses.dataclass(frozen=True)
class FoulAttritionEvaluationResult:
    """Evaluated foul attrition index, extra pitches extracted, and run value."""

    batter_name: str
    bfai_score: float  # Batter Foul Attrition Index (0 to 160)
    surplus_pitches_extracted: float  # Total extra pitches extracted across season
    srar_runs_saved: float  # Starter Removal Acceleration Runs
    attrition_tier: str  # e.g. "EXHAUSTING_FOUL_BALL_GRINDER", "RAPID_DISMISSAL"
    is_exhausting_grinder: bool


class BaseFoulAttritionEngine(Protocol):
    """Polymorphic protocol for foul attrition engines."""

    def evaluate_attrition(
        self,
        metrics: BatterFoulAttritionMetrics,
    ) -> FoulAttritionEvaluationResult:
        """Calculate BFAI score, extra pitches extracted, and SRAR runs."""
        ...


class BatterFoulAttritionEngine:
    """Calculates multi-foul battle endurance and starter attrition (FOUL-ATTRITION-01)."""

    def evaluate_attrition(
        self,
        metrics: BatterFoulAttritionMetrics,
    ) -> FoulAttritionEvaluationResult:
        """Compute BFAI score and pitcher exhaustion run value."""
        # BFAI Score: benchmark 11.0% multi-foul, 3.95 P/PA, 42.0% foul
        multi_bonus = (metrics.multi_foul_pa_rate_pct - 11.0) * 3.2
        ppa_bonus = (metrics.pitches_per_pa - 3.95) * 35.0
        foul_bonus = (metrics.two_strike_foul_rate_pct - 42.0) * 0.8
        bfai = round(max(0.0, 100.0 + multi_bonus + ppa_bonus + foul_bonus), 1)

        # Surplus Pitches & SRAR Runs: extra pitches force early starter hook (~0.032 runs/pitch).
        # surplus_pitches_extracted is a count of *extra* pitches drawn above the
        # benchmark batter, so it floors at zero -- a below-benchmark batter draws
        # no surplus, not a negative one (SRAR already floors the same way).
        pas = max(1, metrics.total_pa_count)
        surplus_p = round(max(0.0, (metrics.pitches_per_pa - 3.95) * pas), 1)
        srar_runs = round(surplus_p * 0.032, 2)

        is_grinder = (
            bfai >= 118.0
            and metrics.multi_foul_pa_rate_pct >= 14.5
            and metrics.pitches_per_pa >= 4.20
        )

        # Tiers
        if is_grinder:
            tier = "EXHAUSTING_FOUL_BALL_GRINDER"
        elif metrics.pitches_per_pa <= 3.50:
            tier = "RAPID_DISMISSAL_FREE_SWINGER"
        elif metrics.multi_foul_pa_rate_pct >= 13.0:
            tier = "ABOVE_AVERAGE_PITCH_EATER"
        else:
            tier = "AVERAGE_FOUL_ATTRITION"

        return FoulAttritionEvaluationResult(
            batter_name=metrics.batter_name,
            bfai_score=bfai,
            surplus_pitches_extracted=surplus_p,
            srar_runs_saved=srar_runs,
            attrition_tier=tier,
            is_exhausting_grinder=is_grinder,
        )


def health_check() -> list[Check]:
    """Operational health check for Batter Foul Attrition Engine (FOUL-ATTRITION-01)."""
    checks: list[Check] = []
    try:
        engine = BatterFoulAttritionEngine()
        grinder = BatterFoulAttritionMetrics("b1", "Brandon Nimmo", 19.0, 4.45, 54.0, 580)
        hacker = BatterFoulAttritionMetrics("b2", "Quick Hacker", 5.0, 3.35, 30.0, 450)

        r_gri = engine.evaluate_attrition(grinder)
        r_hac = engine.evaluate_attrition(hacker)

        if (
            r_gri.attrition_tier == "EXHAUSTING_FOUL_BALL_GRINDER"
            and r_hac.attrition_tier == "RAPID_DISMISSAL_FREE_SWINGER"
        ):
            checks.append(
                Check(
                    "foul attrition engine",
                    True,
                    f"Foul Attrition verified (Nimmo BFAI: {r_gri.bfai_score:.1f})",
                )
            )
        else:
            checks.append(
                Check(
                    "foul attrition engine",
                    False,
                    f"Unexpected foul attrition output: {r_gri}, {r_hac}",
                )
            )
    except Exception as exc:
        checks.append(Check("foul attrition engine", False, str(exc)))
    return checks
