"""Batter Pull-Air Barrel Conversion & True Power Engine (PULL-BARREL-01, ADR-211).

Provides pulled flyball concentration, barrel conversion, and home run surplus modeling:
1. Pull-Air Barrel Conversion Index (PABCI score measuring pull-side power efficiency).
2. Pulled-Air Surplus Home Runs & Run Value (HRs generated by pulling flyballs).
3. Power Archetypes (Optimal Pull-Air Crusher, Dead Center Undervalued, Popup Risk).

Adheres strictly to object-oriented encapsulation, polymorphic protocols, and
point-in-time correctness with zero lookahead leakage.
"""

from __future__ import annotations

import dataclasses
from typing import Protocol

from mlb_baseball.health import Check


@dataclasses.dataclass(frozen=True)
class BatterPullBarrelMetrics:
    """Observed batter flyball pull rate, pull-side barrel rate, and BBE volumes."""

    batter_id: str
    batter_name: str
    flyball_pull_pct: float = 30.0  # League average ~28.0%
    pull_barrel_pct: float = 24.0  # League average ~22.0%
    oppo_barrel_pct: float = 12.0
    pulled_air_count: int = 70
    total_bbe_count: int = 240


@dataclasses.dataclass(frozen=True)
class PullBarrelEvaluationResult:
    """Evaluated pull-air barrel conversion, surplus home runs, and run value."""

    batter_name: str
    pabci_score: float  # Pull-Air Barrel Conversion Index (0 to 160)
    surplus_home_runs: float  # Net surplus HRs generated from optimal pull-air trajectory
    pabsv_runs_saved: float  # Net run production from pull-air power surplus
    power_tier: str  # e.g. "OPTIMAL_PULL_AIR_POWER_CRUSHER", "HARMLESS_POPUP_RISK"
    is_optimal_crusher: bool


class BasePullBarrelEngine(Protocol):
    """Polymorphic protocol for pull-air barrel conversion engines."""

    def evaluate_pull_barrel(
        self,
        metrics: BatterPullBarrelMetrics,
    ) -> PullBarrelEvaluationResult:
        """Calculate PABCI score, surplus home runs, and run value."""
        ...


class BatterPullBarrelEngine:
    """Calculates pull-side airborne power conversion and run value (PULL-BARREL-01)."""

    def evaluate_pull_barrel(
        self,
        metrics: BatterPullBarrelMetrics,
    ) -> PullBarrelEvaluationResult:
        """Compute PABCI index and home run surplus."""
        # PABCI Score: benchmark is 28.0% PullFB, 22.0% PullBarrel, 10.0% gap
        pull_fb_bonus = (metrics.flyball_pull_pct - 28.0) * 2.8
        pull_bar_bonus = (metrics.pull_barrel_pct - 22.0) * 2.4
        gap_bonus = (metrics.pull_barrel_pct - metrics.oppo_barrel_pct - 10.0) * 0.8
        pabci = round(max(0.0, 100.0 + pull_fb_bonus + pull_bar_bonus + gap_bonus), 1)

        # Surplus Home Runs: pulling air balls yields ~0.28 HRs per surplus air ball
        air_count = max(1, metrics.pulled_air_count)
        surplus_hr = round(((metrics.flyball_pull_pct - 28.0) / 100.0) * air_count * 0.28, 2)
        surplus_hr = max(0.0, surplus_hr)
        pabsv = round(surplus_hr * 1.40, 2)

        is_crusher = (
            pabci >= 118.0 and metrics.flyball_pull_pct >= 34.0 and metrics.pull_barrel_pct >= 28.0
        )

        # Tiers
        if is_crusher:
            tier = "OPTIMAL_PULL_AIR_POWER_CRUSHER"
        elif metrics.flyball_pull_pct <= 22.0 and metrics.pull_barrel_pct >= 25.0:
            tier = "DEAD_CENTER_POWER_UNDERVALUED"
        elif metrics.flyball_pull_pct >= 34.0 and metrics.pull_barrel_pct <= 14.0:
            tier = "HARMLESS_PULL_AIR_POPUP_RISK"
        else:
            tier = "AVERAGE_PULL_AIR_PROFILE"

        return PullBarrelEvaluationResult(
            batter_name=metrics.batter_name,
            pabci_score=pabci,
            surplus_home_runs=surplus_hr,
            pabsv_runs_saved=pabsv,
            power_tier=tier,
            is_optimal_crusher=is_crusher,
        )


def health_check() -> list[Check]:
    """Operational health check for Pull-Air Barrel Engine (PULL-BARREL-01)."""
    checks: list[Check] = []
    try:
        engine = BatterPullBarrelEngine()
        crusher = BatterPullBarrelMetrics("b1", "Jose Ramirez", 38.0, 34.0, 10.0, 85, 280)
        popup_risk = BatterPullBarrelMetrics("b2", "Weak Pull Air", 36.0, 12.0, 8.0, 70, 220)

        r_cru = engine.evaluate_pull_barrel(crusher)
        r_pop = engine.evaluate_pull_barrel(popup_risk)

        if (
            r_cru.power_tier == "OPTIMAL_PULL_AIR_POWER_CRUSHER"
            and r_pop.power_tier == "HARMLESS_PULL_AIR_POPUP_RISK"
        ):
            checks.append(
                Check(
                    "pull barrel engine",
                    True,
                    f"Pull Barrel verified (Ramirez PABCI: {r_cru.pabci_score:.1f})",
                )
            )
        else:
            checks.append(
                Check(
                    "pull barrel engine", False, f"Unexpected pull barrel output: {r_cru}, {r_pop}"
                )
            )
    except Exception as exc:
        checks.append(Check("pull barrel engine", False, str(exc)))
    return checks
